### ISSUE TITLE
玩家进服后很快被踢

### ISSUE THREAD

**Issue by Star-Jirachi** [Jissee/JarsAuth#12]
服务器有的玩家进服后被踢，显示这个：
![DHXS4B7CN02Q%B{S@C%0}_L](https://github.com/Jissee/JarsAuth/assets/103431598/8a1fc3cf-55c7-458f-b69b-e270729fcdbe)
服务器控制台没有异常，只显示连接中断。

玩家客户端的log文件显示异常如下：
[053月2024 20:10:14.536] [Thread-47/ERROR] [me.jissee.jarsauth.packet.BroadcastPacket/]: error when sending auth msg
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientPacketListener.m_104910_()" because the return value of "net.minecraft.client.Minecraft.m_91403_()" is null
	at net.minecraftforge.network.simple.SimpleChannel.sendToServer(SimpleChannel.java:87) ~[forge-1.20.1-47.2.1-universal.jar%23613!/:?]
	at me.jissee.jarsauth.packet.PacketHandler.sendToServer(PacketHandler.java:47) ~[JarsAuth-1.20.1-4.4.jar%23532!/:4.4]
	at me.jissee.jarsauth.packet.BroadcastPacket.lambda$handle$4(BroadcastPacket.java:238) ~[JarsAuth-1.20.1-4.4.jar%23532!/:4.4]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[053月2024 20:13:03.939] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!

**Comment by Star-Jirachi** [comment]
抱歉，经过测试不是jarsauth问题
